name: ipykernel tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: [ '3.5', '3.6', '3.7', '3.8', '3.9', 'pypy3' ]
        exclude:
        - os: windows
          python-version: pypy3
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Upgrade packaging dependencies
      run: |
        pip install --upgrade pip setuptools wheel --user
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-
    - name: Install the Python dependencies
      run: |
        pip install --pre --upgrade --upgrade-strategy=eager .[test] codecov
    - name: Install optional dependencies
      run: |
        pip install matplotlib || echo 'failed to install matplolib'
        pip install curio || echo 'failed to install curio'
        pip install trio || echo 'failed to install trio'
    - name: List installed packages
      run: |
        pip freeze
        pip check
    - name: Run the tests
      timeout-minutes: 30
      run: |
        pytest -vv --pyargs ipykernel --cov ipykernel --cov-branch --cov-report term-missing:skip-covered --durations 10
    - name: Coverage
      run: |
        codecov
